### PR TITLE
Typo in docs?

### PR DESCRIPTION
**Pull request by bjornbjorn**
Hey, shouldn't it be $this->EE->load->library() and not $this->EE->load->driver()?

### CODE REVIEW

**Comment by objectivehtml** [comment]
Channel Data is a modified CodeIgniter driver. It's possible a library loader will work, but I wanted to keep everything consistent with CI so I used the driver method to load everything. I don't use the actual CI inheritance class, but it's the same concept. Either method should work though.

http://codeigniter.com/user_guide/general/drivers.html

There are a ton of things I have yet to document about Channel Data - the Utility and Tmpl drivers are among those.

Example:

$this->EE->channel_data->utility->add_prefix('prefix', $vars);
$this->EE->channel_data->utility->reindex($vars, 'some_index');
$this->EE->channel_data->tmpl->parse_string($some_string);

You can write your own drivers by extending the core class and naming the file correctly. Channel Data is meant to be extendible and abstract, which is why I use the drivers nomenclature vs. a library which I few a concrete set of methods.

Thoughts?

**Comment by bjornbjorn** [comment]
Aha, ok .. guess I'm a bit confused :-P .. I've loaded it as a library now btw and it seems to work fine. But anyway, do you have an example of how to use Channel Data as a driver?  (ie. where do I put the Channel_data folder etc.)

**Comment by objectivehtml** [comment]
You put the Channel_data director in the system/libraries or your add-on libraries directory. It should work if you load it as a library (as you pointed out), I just don't have the documentation written that way so people know what it's much more than just a standard library.

Drivers really work the same way as libraries, except they can be extended into subclasses and add new methods without changing the core.

As far as examples, the stuff in the README works well. Sometimes I use Channel Data to create model with polymorphic parameters. So essentially, Channel Data can be a replacement for ActiveRecord at times.

```
public function get_entry($field_id, $entry_id)
{
    return $this->get_entries(array(
        'where' => array(
            'field_id' => $field_id,
            'entry_id' => $entry_id
        )
    ));
}

public function get_entries($params)
{
    return $this->channel_data->get('table_builder_entries', $params);
}
```

**Comment by bjornbjorn** [comment]
> You put the Channel_data director in the system/libraries or your add-on libraries directory. 

Ah, that's the missing link in the docs for me. I tried to put the Channel_data.php etc. files directly in the libraries/ folder, and when loading it with ->driver() didn't work I tried ->library() and that worked so I thought it was a documentation issue.

**Comment by bjornbjorn** [comment]
Thanks for the support ;-) .. I'm closing this pull req.

btw FWIW I think you should add an "Installation" section in the docs where you mention where the files should be placed and recommended practices (I guess if you're creating an addon it'd be best to place it in the libraries/ folder as opposed to the one in system/)

**Pull request closed without merging**
